### ISSUE TITLE
Is "Master" actually fetching master?

### ISSUE THREAD

**Issue by mokagio** [smartdevicelink/sdl_core_docker#1]
I was having a look at `Master/Dockerfile` and noticed that the branch [env var is set to `develop`](https://github.com/smartdevicelink/sdl_core_docker/blob/master/Master/Dockerfile#L13).

```
ENV SDL_CORE_BRANCH develop
```

Wouldn't this result in the develop branch being pulled instead of the expected master one?

**Comment by CMaylone** [comment]
@mokagio Thanks!
